osx_image: xcode8.2
language: objective-c

cache:
  directories:
  - Carthage

before_install:
- carthage bootstrap

script:
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator clean build | xcpretty
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -enableCodeCoverage YES test | xcpretty
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-Mac" -sdk macosx clean build | xcpretty
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-Mac" -sdk macosx -enableCodeCoverage YES test | xcpretty
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' clean build | xcpretty
- set -o pipefail && xcodebuild -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' -enableCodeCoverage YES test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
